### ISSUE TITLE
This completely bricked my Deauther watch

### ISSUE THREAD

**Issue by CodeMeh-1** [mrvodka007/n2d#17]
I was checking if there any new updates and came across this tool. I did the following plugin the watch to the computer via USB. I waited for it to flash and when it did the watches OLED text went crazy and now the watch is completely dead. No text will display the power button doesn't work. Please help

**Comment by mrvodka007** [comment]
Apologies for the delayed response, n2d flashes the default 1MB image for every device. This is a known issue and won't be fixed any time soon. I also must mention that n2d does not do the flashing itself, rather executes a compiled version of esptool.py. As deauther v3 is on the way, stay tuned to [NubImage](https://github.com/mrvodka007/nubimage)

To fix the problem, I would recommend a clean wipe of the deauther. You can download the compiled version of [esptool.py](https://github.com/mrvodka007/nubimage/raw/master/cloudfiles/esptool.dpnd.exe) and run it in CLI: `esptool.dpnd.exe --baud 115200 erase_flash`
